name: RSS Cron Job

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:

      - name: Debug Secret
        run: |
          if [ -z "${{ secrets.RSS_SECRET }}" ]; then
            echo "Secret is EMPTY"
          else
            echo "Secret is SET"
          fi

      - name: Call RSS API
        run: |
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.RSS_SECRET }}" \
          https://plainlyonline.vercel.app/api/rss-fetch